[package]
name = "autochroma"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.5.7"
thiserror = "1.0.50"

hocon = { version = "0.9.0", features = [ "serde-support" ] }
serde = { version = "1.0.192", features = [ "derive" ] }
tokio = { version = "1.34.0", features = [ "full" ] }
